config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :stations, only: [:index, :show]
  resources :trains, only: [:index, :show]

  root to: 'stations#index'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :station

  validates :city, presence: true
  validates :street, presence: true
  validates :number, presence: true

  def to_s
    "#{self.street}, #{self.number}, #{self.city}, #{self.country}"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beverage_store.rb
class BeverageStore < ApplicationRecord
  belongs_to :station

  validates :name, presence: true, uniqueness: true
end

app/models/station.rb
class Station < ApplicationRecord
  has_one :address
  has_many :beverage_stores
  has_many :timetables
  has_many :trains, through: :timetables

  validates :name, presence: true, uniqueness: true
  validates :phone, format: { with: /\A(\+\d ?)?[\(\)0-9\- \.]{10,20}\z/ }
end

app/models/timetable.rb
class Timetable < ApplicationRecord
  belongs_to :train
  belongs_to :station

  validates :day, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 6 }
end

app/models/train.rb
class Train < ApplicationRecord
  has_many :timetables
  has_many :stations, through: :timetables

  validates :name, presence: true
  validates :number, presence: true, uniqueness: true
  validates :wagon_count, numericality: { greater_than_or_equal_to: 2, less_than_or_equal_to: 50 }

  def route
    "#{start_station.name} - #{finish_station.name}"
  end

  def starting_station
    self.timetables.where(arrival_time: nil).first&.station
  end

  def end_station
    self.timetables.where(departure_time: nil).first&.station
  end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController

  protected

  def after_sign_in_path_for(_resource)
    rails_admin_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound,         with: :render_not_found
  rescue_from ActionController::RoutingError,       with: :render_not_found
  rescue_from ::AbstractController::ActionNotFound, with: :render_not_found

  def render_not_found
    render 'errors/error_404', status: 404
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :find_station, only: :show

  def index
    @stations = Station.all
  end

  def show
    @trains = @station.trains
    @beverage_stores = @station.beverage_stores
  end

  private

  def find_station
    @station = Station.where(id: params[:id]).includes(:trains, :beverage_stores).first

    raise ActiveRecord::RecordNotFound unless @station
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :find_train, only: :show

  def index
    @trains = Train.all
  end

  def show
    @timetables = @train.timetables
  end

  private

  def find_train
    @train = Train.where(id: params[:id]).includes(:timetables).first

    raise ActiveRecord::RecordNotFound unless @train
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
  def route(train)
    starting_station = train.starting_station
    end_station = train.end_station
    items = []
    make_link items, starting_station
    make_link items, end_station

    items.join.html_safe
  end

  private

  def make_link(items, station)
    if station
      link = link_to(station.name, station_path(id: station.id))
      items << content_tag(:td, link.html_safe)
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ryosuke</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stations/index.html.erb
<div class="stations">
  <%= link_to('Home', root_path, class: 'home') %>
  <h1>Welcome to RYOSUKE Train Station Pages</h1>
</div>
<table class="station">
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Information</th>
  </tr>
  <% @stations.each do |station| %>
      <tr>
        <td><%= link_to(station.name, station_path(id: station.id)) %></td>
        <td><%= station.address %></td>
        <td><%= station.phone %></td>
        <td><%= station.information %></td>
      </tr>
  <% end %>
</table>

app/views/stations/show.html.erb
<div class="stations">
  <%= link_to('Home', root_path, class: 'home') %>
  <h1><%= @station.name %></h1>
</div>

<table class="train">
  <caption>Trains</caption>
  <tr>
    <th>Name</th>
    <th>Number</th>
    <th>Wagon count</th>
    <th>Starting station</th>
    <th>End station</th>
  </tr>
  <% @trains.each do |train| %>
      <tr>
        <td><%= link_to(train.name, train_path(id: train.id)) %></td>
        <td><%= train.number %></td>
        <td><%= train.wagon_count %></td>
        <%= route train %>
      </tr>
  <% end %>
</table>

<table class="beverage-store">
  <caption>Beverage stores</caption>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <% @beverage_stores.each do |beverage_store| %>
      <tr>
        <td><%= beverage_store.name %></td>
        <td><%= beverage_store.description %></td>
      </tr>
  <% end %>
</table>

<div class="info">
  <div class="station address"><%= @station.address %></div>
  <div class="station phone"><%= @station.phone %></div>
  <div class="station information"><%= @station.information %></div>
</div>

app/views/trains/index.html.erb
<div class="trains">
  <%= link_to('Home', root_path, class: 'home') %>
  <h1>Welcome to RYOSUKE Train Station Pages</h1>
</div>
<table class="station">
  <tr>
    <th>Name</th>
    <th>Number</th>
    <th>Wagon count</th>
    <th>Starting station</th>
    <th>End station</th>
  </tr>
  <% @trains.each do |train| %>
      <tr>
        <td><%= link_to(train.name, train_path(id: train.id)) %></td>
        <td><%= train.number %></td>
        <td><%= train.wagon_count %></td>
        <%= route train %>
      </tr>
  <% end %>
</table>

app/views/trains/show.html.erb
<div class="trains">
  <%= link_to('Home', root_path, class: 'home') %>
  <h1><%= @train.name %></h1>
</div>
<div class="info">
  <div class="train address">Train number: <%= @train.number %></div>
  <div class="train phone">Count of wagon: <%= @train.wagon_count %></div>
</div>
<table class="timetable">
  <caption>Timetable</caption>
  <tr>
    <th>Station</th>
    <th>Arrival time</th>
    <th>Departure time</th>
  </tr>
  <% @timetables.each do |timetable| %>
      <tr>
        <td><%= link_to(timetable.station.name, station_path(id: timetable.station.id)) %></td>
        <td><%= timetable.arrival_time %></td>
        <td><%= timetable.departure_time %></td>
      </tr>
  <% end %>
</table>